source "https://rubygems.org"

# Railsのエッジバージョンを使用する場合: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.0" # Railsのバージョンを指定

# Active RecordでSQLite3をデータベースとして使用
gem "sqlite3", ">= 2.1"

# Pumaウェブサーバーを使用 [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# JSON APIを簡単に構築するためのJBuilder [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Active Modelのhas_secure_passwordを使用 [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windowsにはzoneinfoファイルが含まれていないため、tzinfo-data gemをバンドル
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Rails.cache、Active Job、Action Cable用のデータベースベースのアダプターを使用
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# 起動時間をキャッシュで短縮; config/boot.rbで必要
gem "bootsnap", require: false

# Dockerコンテナとしてこのアプリケーションをどこでもデプロイ [https://kamal-deploy.org]
gem "kamal", require: false

# PumaにHTTPアセットのキャッシュ/圧縮とX-Sendfileアクセラレーションを追加 [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Active Storageのバリアントを使用 [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Cross-Origin Resource Sharing (CORS) を処理するためのRack CORSを使用
# クロスオリジンのAjaxを可能にします。
gem "rack-cors"

group :development, :test do
  # デバッグ用 [https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem]
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # セキュリティの脆弱性を静的分析で検出 [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Rubyのスタイリング [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # 開発環境用のletter_opener_webを追加
  gem "letter_opener_web", group: :development
end


